### PR TITLE
WIP: Add custom renderer for events

### PR DESCRIPTION
**Pull request by sebastienfi**
This pull request adds the opportunity for a custom event renderer function.

Example use : 

```typescript
const eventRenderer = (event: DayJSConvertedEvent, touchableOpacityProps: any) => {
  return (
    <TouchableOpacity
      {...touchableOpacityProps}
      style={[
        ...touchableOpacityProps.style,
        {
          backgroundColor: 'white',
          borderWidth: 1,
          borderColor: 'lightgrey',
          borderLeftColor: event.color
            ? event.color
            : touchableOpacityProps.style[2].backgroundColor,
          borderLeftWidth: 10,
          borderStyle: 'solid',
          borderRadius: 6,
          alignItems: 'center',
          justifyContent: 'center',
        },
      ]}
    >
      {event.end.diff(event.start, 'minute') < 32 && showTime ? (
        <Text style={{ ...commonStyles.eventTitle, color: 'black' }}>
          {event.title},<Text style={styles.eventTime}>{event.start.format('HH:mm')}</Text>
        </Text>
      ) : (
        <>
          <Text style={{ ...commonStyles.eventTitle, color: 'black' }}>{event.title}</Text>
          <Text style={styles.eventTime}>{formatStartEnd(event)}</Text>
          {event.children && event.children}
        </>
      )}
    </TouchableOpacity>
  )
}

export const customRendererEvents = [
  {
    title: 'Custom Renderer',
    start: dayjs().add(1, 'day').set('hour', 12).set('minute', 0).toDate(),
    end: dayjs().add(1, 'day').set('hour', 15).set('minute', 30).toDate(),
    eventRenderer,
  },
  {
    title: 'Custom reminder',
    start: dayjs().set('hour', 16).set('minute', 0).toDate(),
    end: dayjs().set('hour', 17).set('minute', 0).toDate(),
    color: 'purple',
    eventRenderer,
  },
]
```

### CODE REVIEW

**Comment by acro5piano** [comment]
@sebastienfi 

Thank you for the PR!! It's an amazing feature!!
Can you add the feature to the documentation (README)? It could be helpful if the example you wrote is pasted to somewhere in README too!

https://github.com/acro5piano/react-native-big-calendar#api-documentation

**Comment by sebastienfi** [comment]
@acro5piano Done.

**Comment by sebastienfi** [comment]
Updated doc to match fixes from https://github.com/acro5piano/react-native-big-calendar/pull/360

**Comment by acro5piano** [comment]
Released on v0.8.0.

**Pull request merged**
