### PR TITLE
Support for events that end after start date, and adds option to hide the nowIndicator.

### PR DESCRIPTION
**Pull request by OffensivelyBad**
I also did a little bit of prop cleanup, to keep the props in alphabetic order and keep functions at the bottom of the props list.

### CODE REVIEW

**Comment by acro5piano** [comment]
@OffensivelyBad 
Thank you for your PR!
Could you add the following things as usual?

- Document in README
- A simple usage to [Storybook](https://github.com/acro5piano/react-native-big-calendar/blob/master/stories/desktop.stories.tsx)

**Comment by OffensivelyBad** [comment]
Hi @acro5piano I added documentation and stories for the nowIndicator.  Let me know if there's anything else.

Thanks!

**Comment by acro5piano** [comment]
@OffensivelyBad 
Thanks very much!!

**Comment by acro5piano** [comment]
Released on [v0.6.0](https://github.com/acro5piano/react-native-big-calendar/releases/tag/v0.6.0)

**Pull request merged**
