### PR TITLE
feat: Agenda/Schedule mode

### PR DESCRIPTION
**Pull request by charithAmila**
PR for issue https://github.com/acro5piano/react-native-big-calendar/issues/710

Implemented `schedule` mode.

Test:
Render Calender Component with `schedule` mode.
All events should appear with the Schedule view as the screenshot.

Screenshot 2023-10-17 at 1 42 11 AM

### CODE REVIEW

**Comment by charithAmila** [comment]
Hey @acro5piano 
I committed the code changes for the basic Agenda/Schedule mode. I would like to know your feedback on this before opening the PR.

**Comment by acro5piano** [comment]
@charithAmila Thanks, it looks fantastic! 

Can you edit these files too? Storybook will help me to check the UI.

- API Doc: https://github.com/acro5piano/react-native-big-calendar/blob/main/README.md#api-documentation
- Storybooks:
  - https://github.com/acro5piano/react-native-big-calendar/blob/main/stories/mobile.stories.tsx
  - https://github.com/acro5piano/react-native-big-calendar/blob/main/stories/desktop.stories.tsx

**Comment by charithAmila** [comment]
> @charithAmila Thanks, it looks fantastic!
> 
> Can you edit these files too? Storybook will help me to check the UI.
> 
> * API Doc: https://github.com/acro5piano/react-native-big-calendar/blob/main/README.md#api-documentation
> * Storybooks:
>   
>   * https://github.com/acro5piano/react-native-big-calendar/blob/main/stories/mobile.stories.tsx
>   * https://github.com/acro5piano/react-native-big-calendar/blob/main/stories/desktop.stories.tsx

Sure I will do

**Comment by charithAmila** [comment]
@acro5piano 
I updated the storybook files. I will update the README during the weekend.

**Comment by acro5piano** [comment]
@charithAmila Thanks!

**Comment by charithAmila** [comment]
@acro5piano README and storybook files updated.

**Comment by acro5piano** [comment]
@charithAmila Thank you for your contribution!

**Comment by acro5piano** [comment]
Released on v4.6.0

**Pull request merged**
