### PR TITLE
fix infinite setState onChangeDate

### PR DESCRIPTION
**Pull request by mubashiralisiddiqui**
resolve infinte rendering issue on onChange Date

Related: https://github.com/acro5piano/react-native-big-calendar/issues/712

### CODE REVIEW

**Comment by acro5piano** [comment]
Thanks for your pull request!

```diff
  React.useEffect(() => {
    if (onChangeDate) {
      onChangeDate([dateRange[0].toDate(), dateRange.slice(-1)[0].toDate()])
    }
- }, [dateRange, onChangeDate])
+ }, [dateRange])
```

**Comment by mubashiralisiddiqui** [comment]
> ```diff
> + /* eslint-disable */
> + }, [dateRange])
> ```

I have tried it but it's not working

**Comment by mubashiralisiddiqui** [comment]
> ```diff
>  /* eslint-disable */
> ```

by the way working MR is ready I have disable eslint for that specific part you can merge it now

**Comment by acro5piano** [comment]
@mubashiralisiddiqui Thanks! I'll confirm it and merge this ASAP

**Comment by acro5piano** [comment]
Thank you for your contribution!

**Pull request merged**
