### PR TITLE
Feature : Clickable More Label

### PR DESCRIPTION
**Pull request by Sheena1234**
Added new attribute OnPressMoreLabel which has two arguments Events, Date.

### CODE REVIEW

**Comment by acro5piano** [comment]
Thanks for the PR.
Is it ready to merge? 

Also, it would be gald if you add the prop here (not mandatory):

https://github.com/acro5piano/react-native-big-calendar/blob/4f50d6ce133c8253f14cfd0d80f38c93e055eb6d/stories/desktop.stories.tsx#L62-L81

**Comment by Sheena1234** [comment]
Hi, Yes the branch is ready to merge. 
and Sure I will add the prop there

**Comment by acro5piano** [comment]
Released on v4.1.0

**Comment by Sheena1234** [comment]
Thank you so much!!

**Pull request merged**
