### PR TITLE
Added month separator for schedule view

### PR DESCRIPTION
**Pull request by ARedmanDodd**
#### Added Full-Width Month Separator and Custom Styling Option

- **Month Separator Component**: A new full-width month separator has been introduced to visually indicate the transition between months in the event schedule view. The separator displays the month and year (e.g., "October 2024") and spans the entire width of the container.
  - The separator is styled with center alignment, padding, and the primary theme color for visibility.

- **Custom Styling Option**: Added a new `scheduleMonthSeparatorStyle` prop to the `Schedule` component. This allows users to apply custom styles to the month separator, providing flexibility for different use cases.

- **Separator Integration**:
  - The month separator is rendered above each new month’s event group in the `renderFlatListItem` function.
  - Logic ensures that the separator only appears when transitioning to a new month, based on event dates.

- **Storybook Updates**: Updated the corresponding stories to reflect these changes and showcase the month separator functionality with customizable styles. 
  - Added 2 extra events to the story to highlight the new feature and demonstrate how the month separator works in different contexts.

#### Impact
- Provides a clear visual distinction between months in the event schedule, improving usability.
- The `scheduleMonthSeparatorStyle` prop enhances flexibility by allowing customization of the separator’s appearance.

### CODE REVIEW

**Comment by acro5piano** [comment]
@ARedmanDodd Thanks! That change is fantastic. The code looks great to me. Just one thing, can you fix this TSC check? Best regards

https://github.com/acro5piano/react-native-big-calendar/actions/runs/11795110129/job/33080336865?pr=1115

**Review by acro5piano — CHANGES_REQUESTED** [review]
Please fix `tsc` error

**Comment by ARedmanDodd** [comment]
Thanks for the feedback, I'll get that fixed up now 👍

**Comment by ARedmanDodd** [comment]
Changes submitted:

**fix: update monthSeparatorStyle type to TextStyle for color support**

- Replaced `ViewStyle` with `TextStyle` for `monthSeparatorStyle` in `CalendarContainerProps` to allow the `color` property.  
- Fixed TypeScript error (`TS2353`) related to unsupported `color` in `ViewStyle`.  

This change resolves the `tsc` error and ensures compatibility with style properties requiring `color`.

**Comment by acro5piano** [comment]
@ARedmanDodd Thank you for your contribution!

**Comment by ARedmanDodd** [comment]
Thank you for accepting it!

**Pull request merged**
