### PR TITLE
Drag and drop feature

### PR DESCRIPTION
**Pull request by gabrielmouallem**
This is my first ever PR inside an open source project, probably need many adjustments.

### CODE REVIEW

**Comment by acro5piano** [comment]
This is very interesting. Why did you close it?

**Comment by gabriel-mouallem** [comment]
> This is very interesting. Why did you close it?

I edited the package json in order to make my "npm publish" and I think it's too early to open the PR. I'm planning to make the drag and drop feature only when long pressing, etc...

**Comment by acro5piano** [comment]
@gabriel-mouallem Thanks! If you are ready, please let me know.

**Comment by rdewolff** [comment]
Any update on this feature?

**Comment by itajenglish** [comment]
👀 Bumping for updates on this as well

**Comment by iamproparnadas** [comment]
> > @gabriel-mouallem Thanks! If you are ready, please let me know.
> 
> Sure! 😁

Hi is there any update on this?

**Comment by gabrielmouallem** [comment]
> > > @gabriel-mouallem Thanks! If you are ready, please let me know.
> > 
> > 
> > Sure! 😁
> 
> Hi is there any update on this?

It’s been a while since I implemented this feature, and to be honest, it could be much better in terms of clean code and how we calculate the event position during drag and drop. There were even some bugs while dragging. My suggestion is to review how I developed it back then, but to create a new version from scratch. I don’t recommend forking it, as it is outdated compared to the current library and doesn’t adhere to clean code standards in its development.

Feel free to adjust any parts as needed!

**Pull request closed without merging**
