### PR TITLE
Add pan left and right to the header

### PR DESCRIPTION
**Pull request by titanve**
image

### CODE REVIEW

**Comment by titanve** [comment]
@acro5piano please your review 🙏

**Comment by acro5piano** [comment]
I'll take a look on the weekend (best effort though)

**Comment by acro5piano** [comment]
@titanve Did you test it on iOS/Android?

**Comment by titanve** [comment]
> @titanve Did you test it on iOS/Android?

@acro5piano no, can you teach me how to test it?

**Comment by acro5piano** [comment]
> > @titanve Did you test it on iOS/Android?
> 
> @acro5piano no, can you teach me how to test it?

```
```

**Comment by titanve** [comment]
@acro5piano what do you use in order to test on a real device? Expo?

**Comment by titanve** [comment]
@acro5piano I'm getting some errors when trying to run `yarn ios`. I'm gonna try again later 🙏

**Comment by titanve** [comment]
@acro5piano I always compile my app to iOS and Android so I test this component in both environments.

**Comment by titanve** [comment]
@acro5piano I could make it work in the iOS simulator:
image

**Comment by titanve** [comment]
@acro5piano this is the list of files changed/created in order to make the iOS simulator run:
image

**Comment by acro5piano** [comment]
Sorry, I misunderstand this PR's point. I thought `pan` meant `panResponder` which is RN's gesture handler, so I asked you to run the demo RN app to check the gesture handler is working correctly. In fact, you are adding components which changes current date on the header.

This library aims to implement gcal/outlook style calendar, and it is not common that left & right arrow components on the calendar header. Thus I can't accept this feature to keep this library simple and easy to understand.

Also, You can insert your own `renderHeader` in order to implement what you want to do.

However, thank you for your PR and past contributions! If you have any questions, feel free to comment here.

Thanks

**Pull request closed without merging**
